### ISSUE TITLE
Out-of-place Question: How to Add a New Language to The Algorithms?

### ISSUE THREAD

**Issue by maoif** [TheAlgorithms/Clojure#10]
I've written some algorithms in Scheme (at https://github.com/maoif/Algorithms-in-Scheme) and have emailed The Algorithms asking how to include the repo like a month ago, but there's no reply...

So does any one here know how to?

**Comment by fr33m0nk** [comment]
Hi @maoif, you can contact @dynamitechetan for this.
He can help you out.
